### ISSUE TITLE
yaml parsing has bug with same-title entries

### ISSUE THREAD

**Issue by hrmacbeth** [leanprover-community/leanprover-community.github.io#244]
In the section "Hilbert spaces" of the `undergrad.yaml` file, there are two entries called "its completeness".  It makes sense in context:
```yaml
...
dual space: 'normed_space.dual.normed_space'
Riesz representation theorem: 'inner_product_space.to_dual'
inner product space $l^2$: 'lp.inner_product_space'
its completeness: 'lp.complete_space'
inner product space $L^2$: 'measure_theory.L2.inner_product_space'
its completeness: 'measure_theory.Lp.complete_space'
...
```
On the current display of the website, the first "its completeness" links to entry for the second "its completeness", and the second "its completeness" does not appear at all.
